import {API_URL,
LIST_CATEGORIES,
FILTER_BY_CATEGORY,
LOOKUP_MEAL_BY_ID,
IMAGE_URL,
MEAL_THUMBNAIL,
INGREDIENT_THUMBNAIL,
INGREDIENT_THUMBNAIL_SMALL} from '@env';

export default {API_URL,
    LIST_CATEGORIES,
    FILTER_BY_CATEGORY,
    LOOKUP_MEAL_BY_ID,
    IMAGE_URL,
    MEAL_THUMBNAIL,
    INGREDIENT_THUMBNAIL,
    INGREDIENT_THUMBNAIL_SMALL};